s%% Candidate regressors
%  Xq = [w1.^2+w2.^3-w3.^2-w4.^2,...
%      U./w,...
%      U.*w,...
%      U.*W.*w,...
%      U.*W,...
%      q_filt,...
%      W.*w,...
%      W./w];

%  Xq = [U.*wf,...
%        U.^2.*wf,...
%        W.*wf,...
%        W.^2.*wf,...
%        U.*W.*wf,...
%        q_filt.*wf,...
%        U.*wr,...
%        U.^2.*wr,...
%        W.*wr,...
%        W.^2.*wr,...
%        U.*W.*wr,...
%        q_filt.*wr,...       
%        U,...
%        U.*U,...
%        W,...
%        W.^2,...
%        U.*W,...
%        q_filt];

Xq = [U,...
      U.*wf,...
      U.*wr,...
      U.*W,...
      W,...
      q_filt,...
      U.*W.*wf,...
      U.*W.*wr,...
      W.*wf,...
      W.*wr,...
      U.^2,...
      U.^2.*wf,...
      U.^2.*wr,...
      W.^2.*wf,...
      W.^2.*wr,...
];

 Xp = [w1.^2-w2.^2-w3.^2+w4.^2,...
     V.*abs(V),...
     V./w,...
     V.*w,...
     V.*W.*w,...
     V.*W,...
     p_filt,...
     V.*w,...
     V./w];

 Xx = [U.*abs(U),...
       U.*w_s,...
       sign(U).*W,...
       sign(U).*q_filt,...
       sign(U).*w_s];
 
 Xz = [U.^2, ...
       abs(U).*W, ...
       abs(U).*w, ...
       W.^2, ...
       W.*w, ...
       w.^2, ...
       abs(U).*W.*w, ...
       U.^2.*W, ...
       U.^2.*w, ...
       abs(U).*W.^2, ...
       W.^2.*w, ...
       abs(U).*w.^2, ...
       W.*w.^2];
%% X and Z selection
X = Xq;
z = yq;
%% Regression using permanent regressors
A = Aq.value; %Here are permanent regressors

[k,y] = OLS(A,z);

%% Choose method
model_structure_method = 'orthogonal';
switch model_structure_method
    case 'orthogonal'
        orthogonal_model_structure;
    case 'stepwise'
        stepwise_model_structure;
    otherwise
        error('Unknown model structure selection method');
end